### ISSUE TITLE
How to integrate the compiled libwebrtc.aar back into android project

### ISSUE THREAD

**Issue by gbaski** [abdularis/libwebrtc-android#1]
I found your article on WebRTC from source very helpful. 
I stuck at the point of integrating the compiled libwebrtc.aar back into Android project.

What are the Gradle configurations required and files to copy back into android project? 

Use-case: Compile WebRTC framework along with openh264 software codec.
Command: `tools_webrtc/android/build_aar.py --extra-gn-args='target_os="android" rtc_use_h264=true is_debug=false'`

**Comment by abdularis** [comment]
you can create a new android module in your android project, or create a maven repository so you can sync and add the library using implementation dependencies in the gradle build as usual, you can go to repo branch [here for example](https://github.com/abdularis/libwebrtc-android/tree/repo)
